### ISSUE TITLE
Decide on the persist layer

### ISSUE THREAD

**Issue by lipinskipawel** [lipinskipawel/LAN-Game#9]
There are two ways of storing data from the LAN-Game application.
1. [Heroku solution](https://www.heroku.com/free)
2. [AWS solution](https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all)

## Pros Heroku:
- a standalone cloud application
- possibility of implementing much more than simply storing layer
- big and already concrete knowledge of Postgres

## Cons Heroku:
- a need to create and maintain another repository
- after 30 min application goes to sleep stage

## Pros AWS:
- a huge amount of volume
- zero downtime
- reduce the complexity of another repo

## Cons AWS:
- need to learn how to deal with NoSQL databases

@PatrykMilewski 
What do you think?

**Comment by PatrykMilewski** [comment]
https://elements.heroku.com/addons/mongolab

**Comment by lipinskipawel** [comment]
Stack:
- Heroku
- MongoDB
- Micronaut
- Gradle
